[workspace]
resolver = "2"
members = [
    "crates/i5h",
    "crates/i5h-pg",
    "crates/i5h-http",
    "examples/docs/kernel",
    "examples/docs/server",
    "examples/docs/difftest",
    "crates/i5h-sql",
    "crates/i5h-token",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
i5h = { path = "crates/i5h" }
i5h-pg = { path = "crates/i5h-pg" }
i5h-http = { path = "crates/i5h-http" }
i5h-token = { path = "crates/i5h-token" }
i5h-sql = { path = "crates/i5h-sql" }
docs-kernel = { path = "examples/docs/kernel" }
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "signal"] }
tokio-postgres = "0.7"
deadpool-postgres = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
proptest = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
